### PR TITLE
Switch from json-parse-better-errors to json5.

### PR DESCRIPTION
**Pull request by joelday**
Test coverage unchanged. Thanks!

### CODE REVIEW

**Comment by KenanY** [comment]
I'm hesitant about this change, since json5 supports a superset of the syntax that `JSON.parse` and `json-parse-better-errors` support. As a result of this change, would package authors begin using JSON5 syntax in their `package.json`? Could be disastrous since other tooling (i.e. Node.js) expect `package.json` to be simply `JSON.parse`-able.

**Comment by joelday** [comment]
@KenanY Agreed that the implications are significant, however to my knowledge NPM always relies on this package when deserializing package.json files. Obviously I could be mistaken.

**Comment by joelday** [comment]
@KenanY Of course what follows then, however, is what their position would be on allowing it within the package ecosystem to begin with.

**Comment by KenanY** [comment]
> NPM always relies on this package when deserializing package.json files

[Node.js itself](https://github.com/nodejs/node/blob/master/lib/internal/modules/cjs/loader.js#L154-L173) expects `package.json` to be `JSON.parse`-able, so we should make sure that they are okay with this before introducing it into the ecosystem.

**Comment by KenanY** [comment]
Related: https://github.com/nodejs/node/issues/24022

**Comment by zkat** [comment]
We won't support json5 any time soon, and it'sa discussion that's happened way too many times for me to engage again.

**Pull request closed without merging**
