### PR TITLE
Allow multiple lines for the `scripts` directive.

### PR DESCRIPTION
**Pull request by WebReflection**
Writing long lines of sh/bash is not easy to maintain.
Allowing within the `scripts` section also an Array
would make it easier to read, write, and maintain
more complex tasks based on `npm run task`

### CODE REVIEW

**Comment by WebReflection** [comment]
Apologies in advance if already discussed, there's also a `// This is never allowed, and only causes problems` comment in there so I'm pretty sure it was, however, I don't see any concrete problem in substituting a possible array with a joined string.

This would make packages like this possible:
```js
{
  "name": "test",
  "version": "0.0.0",
  "description": "test",
  "main": "test.js",
  "dependencies": {},
  "devDependencies": {},
  "scripts": {
    "maybe": [
      "echo 'maybe it is better'",
      "echo 'to allow multiple lines'",
      "if [ \"\" == \"\" ]; then",
      "  echo \"isn't it?\"",
      "fi"
    ]
  },
  "author": "",
  "license": "ISC"
}
```

Thanks for considering this.

**Comment by WebReflection** [comment]
bump

**Comment by Judahmeek** [comment]
I support this PR and would like to hear an explicit reason if this PR can't be accepted.

**Comment by zkat** [comment]
I'm going to have to turn this down -- this sort of change will create a serious issue for older package managers. I can't even really have a discussion of the relative merits of the idea itself, because the cost is so high (serious fragmentation of the registry), that it's just a non-starter in that sense.

npm scripts have always meant to be used for relatively simple use-cases. If you want to manage longer scripts, consider using separate script files, `node_modules/.hooks`, or tools intended for more advanced processes, like gulp, grunt, or broccoli.

Thanks for taking the time to submit this. I know it's been a long time before this reply. I wish the CLI weren't so generally constrained by the needs of the registry, but that's just part of what we've gotta deal with. Cheers ❤️

**Pull request closed without merging**
