### PR TITLE
do not add node-gyp script for just any *.gyp file

### PR DESCRIPTION
**Pull request by KenanY**
node-gyp specifically needs a `binding.gyp`.

Fixes https://github.com/npm/npm/issues/9816

### CODE REVIEW

**Comment by KenanY** [comment]
(not sure what "subsystem" to put in the commit message because only `src:` has been used in `read-json.js` and it was for `standard`izing)

**Comment by othiym23** [comment]
Looks good, probably semver-major tho because there are probably people relying on the current behavior without knowing about it.

**Comment by KenanY** [comment]
@othiym23 I won't argue with that :)

**Comment by mikemorris** [comment]
Could https://github.com/npm/fstream-npm/blob/31b1e28d81d8324411c49a8f7ae7766e3750ac24/fstream-npm.js#L300-L306 be dropped in the same semver-major release? Hit this surprising behavior in https://github.com/npm/npm/issues/10243 while trying to `npm pack` a Node native addon that uses gyp for the C++ core lib too.

**Comment by othiym23** [comment]
@mikemorris Do you want to take a stab at putting together a patch for that? That's a reasonable request, and you have a little time, because I don't see a way for us to do this as a semver-major for _this_ package without making it semver-major for npm itself. `npm@4` may be coming sooner than people expect.

**Comment by mikemorris** [comment]
@othiym23 Started working on this and I'm a bit confused as to what https://github.com/npm/fstream-npm/blob/d57b6b24f91156067f73417dd8785c6312bfc75f/test/ignores.js#L42 is testing, since https://github.com/npm/fstream-npm/blob/d57b6b24f91156067f73417dd8785c6312bfc75f/fstream-npm.js#L303-L309 only modifies `entry.path`.

**Pull request closed without merging**
